"""initial schema

Revision ID: 1781f6b77855
Revises: 
Create Date: 2026-06-10 23:57:06.884809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1781f6b77855'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocos_rotina',
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora_inicio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora_fim', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=False),
    sa.Column('dias_semana', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_especifica', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habitos',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', sa.Float(), nullable=True),
    sa.Column('unidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbox',
    sa.Column('conteudo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_destino', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('arquivado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pastas',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pai_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pai_id'], ['pastas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conteudo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('propriedades', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_objeto',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_campos', sa.JSON(), nullable=True),
    sa.Column('schema_relacoes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conteudo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pasta_id', sa.Integer(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('propriedades', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('atualizado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pasta_id'], ['pastas.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_objeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries_salvas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_objeto_id', sa.Integer(), nullable=False),
    sa.Column('visualizacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campo_agrupamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filtros', sa.JSON(), nullable=True),
    sa.Column('ordem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_objeto_id'], ['tipos_objeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_habito',
    sa.Column('habito_id', sa.Integer(), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('justificativa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('excecao_justificada', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habito_id'], ['habitos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefas',
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prioridade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tempo_estimado', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bloco_id', sa.Integer(), nullable=True),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('propriedades', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bloco_id'], ['blocos_rotina.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_objeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conexoes_notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_origem_id', sa.Integer(), nullable=False),
    sa.Column('nota_destino_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['nota_destino_id'], ['notas.id'], ),
    sa.ForeignKeyConstraint(['nota_origem_id'], ['notas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nota_origem_id', 'nota_destino_id', 'tipo', name='uq_conexao')
    )
    op.create_table('flashcards',
    sa.Column('nota_id', sa.Integer(), nullable=True),
    sa.Column('pergunta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resposta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intervalo', sa.Float(), nullable=False),
    sa.Column('facilidade', sa.Float(), nullable=False),
    sa.Column('revisoes', sa.Integer(), nullable=False),
    sa.Column('ultima_revisao', sa.DateTime(), nullable=True),
    sa.Column('proxima_revisao', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_tags',
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('nota_id', 'tag_id')
    )
    op.create_table('sessoes_pomodoro',
    sa.Column('contexto_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contexto_id', sa.Integer(), nullable=True),
    sa.Column('duracao_min', sa.Integer(), nullable=False),
    sa.Column('finalizado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resumo_nota_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['resumo_nota_id'], ['notas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessoes_pomodoro')
    op.drop_table('notas_tags')
    op.drop_table('flashcards')
    op.drop_table('conexoes_notas')
    op.drop_table('tarefas')
    op.drop_table('registros_habito')
    op.drop_table('queries_salvas')
    op.drop_table('notas')
    op.drop_table('tipos_objeto')
    op.drop_table('templates')
    op.drop_table('tags')
    op.drop_table('pastas')
    op.drop_table('inbox')
    op.drop_table('habitos')
    op.drop_table('blocos_rotina')
    # ### end Alembic commands ###
