"""add ordem field to nota and update tipoobjeto schema_campos seed

Revision ID: c964110adec5
Revises: 1781f6b77855
Create Date: 2026-06-12 01:13:27.463368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c964110adec5'
down_revision: Union[str, Sequence[str], None] = '1781f6b77855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas', sa.Column('ordem', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas', 'ordem')
    # ### end Alembic commands ###
